#include<iostream>
using namespace std;
int main(){
    long long num,x,y,z;
    cin>>num;
   x=num%10;
   y=((num%100)-(num%10))/10;
   z=((num%1000)-(num%100))/100;
   if(x>y&&x>z){
    cout<<x;
    if(y>z){
        cout<<y<<z;
    }
    if(z>y){
        cout<<z<<y;
    }
   }
   if(y>x&&y>z){
    cout<<y;
    if(x>z){
        cout<<x<<z;
    }
    if(z>x){
        cout<<z<<x;
    }
   }
   if(z>y&&z>x){
    cout<<z;
    if(x>y){
        cout<<x<<y;
    }
    if(y>x){
        cout<<y<<x;
    }
   }
   if(x==y&&x==z){
    cout<<x<<y<<z;
   }
   if(x>y&&y==z){
    cout<<x<<y<<z;
   }
   if(y>x&&x==z){
    cout<<y<<x<<z;
   }
   if(z>x&&x==y){
    cout<<z<<x<<y;
   }
   if(x>y&&x==z){
    cout<<x<<z<<y;
   }
   if(y>x&&y==z){
    cout<<y<<z<<x;
   }
   if(z>x&&z==y){
    cout<<z<<y<<x;
   }
   if(z>y&&x==z){
    cout<<x<<z<<y;
   }
}